# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Juan Manuel ARIZA
email: juanmanuelariza@gmail.com
description: "Just a few words from a young researcher"
baseurl: "/Ariza-JM" # the subpath of your site, e.g. /blog
url: "https://dr-juanchito.github.io"
logo: /Ariza-JM/assets/photo_cv.jpg 

# Build settings
markdown: kramdown
remote_theme: "mmistakes/so-simple-theme"

# Footer Links
footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/ariza-juanmanuel/
    icon: fab fa-fw fa-linkedin
  - title: Gmail
    url: mailto:juanmanuelariza@gmail
    icon: fab fa-fw fa-envelope
  - title: CV
    url: ({{ site.url }}/assets/CV_ARIZA-JM.pdf)
    icon: fab fa-fw fa-graduation-cap